#!/usr/bin/env ruby

require 'rubygems'
require 'bundler'
require 'net/http'
require 'net/https'
require 'uri'
require 'commander/import'
require_relative './actions/deploy'
require_relative './actions/gobierto_data_import'

# :name is optional, otherwise uses the basename of this executable
program :name, 'Populate Tools'
program :version, '1.0.0'
program :description, 'Populate Tools idem'

command :release do |c|
  c.syntax = 'pt release <branch-name>'
  c.description = 'Releases a branch to staging'
  c.action do |args, options|
    branch = args.first
    current_status = `git status -z`
    if current_status.empty?
      %x( git checkout #{branch} )
      %x( git pull origin #{branch} )
      %x( git checkout staging )
      %x( git pull origin staging )
      %x( git merge #{branch} --no-edit )
      %x( git push origin staging )
      application_name = File.basename(Dir.pwd)
      Actions::Deploy.run(application_name, "staging")
    else
      say "There are changes in the current branch. Release aborted"
    end
  end
end

command :deploy do |c|
  c.syntax = 'pt deploy <project> <environment>'
  c.description = 'Calls deploy bot. Requires to setup the environment variable DEPLOY_BOT_TOKEN'
  c.action do |args, options|
    application_name = args.first
    environment = args.last
    Actions::Deploy.run(application_name, environment)
  end
end

command :log do |c|
  c.syntax = 'pt log <server> <project>'
  c.description = 'Tails a remote log'
  c.action do |args, options|
    server = args[0]
    project = args[1]

    if server == "staging01"
      project = "#{project}_staging"
      log_file_name = "staging.log"
    else
      log_file_name = "production.log"
    end

    system("/usr/bin/ssh #{server} 'tail -f /var/www/#{project}/shared/log/#{log_file_name}'")
  end
end

command :pr do |c|
  c.syntax = 'pt pr'
  c.description = 'Creates a new PR for the current branch'
  c.action do |args, options|
    branch = `git branch --show-current`
    repository_url = `git config --get remote.origin.url`
    organization = repository_url.split(':').last.split('/').first
    project = File.basename(Dir.getwd)
    pr_url = "https://github.com/#{organization}/#{project}/pull/new/#{branch}"

    system("open #{pr_url}")
  end
end

command :gobierto_data_import do |c|
  c.syntax = 'pt gobierto_data_import <gobierto_host> <dataset_name> <table_name> <data_file> [schema_file (optional)]'
  c.description = 'Imports a dataset in gobierto data. Requires to setup the environment variable GOBIERT_DATA_ADMIN_TOKEN'
  c.action do |args, options|
    Actions::GobiertoDataImport.run(args)
  end
end
